#!/bin/bash
#------------------------------------------------------------------------------

echo "- Remove junk files"
( echo y | ( set -x ; clean ) )
echo

#------------------------------------------------------------------------------

echo "- Remove python caches"
( set -x ; find . -depth -name __pycache__ -print -exec rm -rf \{\} \; )
echo

#------------------------------------------------------------------------------

echo "- Remove files generated by grammar-tool"

# alias gt=' b=./tool && PYTHONPATH=${b} ${b}/scripts/grammar-tool '

function gt_clean() {
    tool=./tool
    export PYTHONPATH=${tool}
    for style in "$@" ; do
        ( set -x ; ${tool}/scripts/grammar-tool --init --style ${style} clean )
    done
}

GT_STYLES="antlr4 lark peg pegen"
# GT_STYLES="antlr4 lark pegen"

unset cleaned
for style in ${GT_STYLE} ; do
    if [ -e this.${style} -o -e start..${style} ] ; then
        gt_clean ${style}
        cleaned='true'
    fi
done

if [ -z "${cleaned}" ]; then
    gt_clean ${GT_STYLES}
fi

echo

#------------------------------------------------------------------------------
