#!/bin/bash
#------------------------------------------------------------------------------

echo "- In test-files, remove files generated by grammar-tool"

# alias gt=' b=./tool && PYTHONPATH=${b} ${b}/scripts/grammar-tool '

function gt_clean() {
    tool=./tool
    export PYTHONPATH=${tool}
    for style in "$@" ; do
        ( cd test-files ; set -x ; ${tool}/scripts/grammar-tool --init --style ${style} clean )
    done
}

GT_STYLES="antlr4 lark peg pegen"
# GT_STYLES="antlr4 lark pegen"

unset cleaned
for style in ${GT_STYLE} ; do
    if [ -e this.${style} -o -e start..${style} ] ; then
        ( cd test-files ; gt_clean ${style} )
        cleaned='true'
    fi
done

if [ -z "${cleaned}" ]; then
    ( cd test-files ; gt_clean ${GT_STYLES} )
fi

echo

#------------------------------------------------------------------------------

echo "- Remove junk files"
( echo y | ( set -x ; clean ) )
echo

#------------------------------------------------------------------------------

echo "- Remove python and mypy caches, work areas, etc."
( set -x ; find . -depth -name __pycache__    -print -exec rm -rf \{\} \; )
( set -x ; find . -depth -name .mypy_cache    -print -exec rm -rf \{\} \; )
( set -x ; find . -depth -name .pytest_cache  -print -exec rm -rf \{\} \; )
( set -x ; find . -depth -name .tox           -print -exec rm -rf \{\} \; )
( set -x ; find . -depth -name .eggs          -print -exec rm -rf \{\} \; )
( set -x ; find . -depth -name work           -print -exec rm -rf \{\} \; )
echo

#------------------------------------------------------------------------------
